# Generated by Django 4.1.7 on 2023-03-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('auther', models.CharField(max_length=255)),
                ('describtion', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('afterdiscont', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instock', models.BooleanField(default=True)),
                ('isactive', models.BooleanField(default=True)),
                ('whight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
    ]
